env:
  global:
    - NODE_VERSION="8"
matrix:
  include:
    - os: linux
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-26.0.2
          - android-27
        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - nvm install $NODE_VERSION
      install:
        - export ANDROID_HOME=$HOME/android-sdk
      before_script:
        - npm install -g flutter-cli
      script:
        - cd device_calendar/example
        - flutter build apk
    - os: osx
      language: generic
      osx_image: xcode10.2
      before_install:
        - nvm install $NODE_VERSION
      before_script:
        - npm install -g flutter-cli
      script:
        - cd device_calendar/example
        - flutter build ios --release --no-codesign --verbose
cache:
  directories:
    - $HOME/.pub-cache
