name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.4.0
homepage: https://github.com/builttoroam/device_calendar/tree/master

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  timezone: ^0.9.1
  rrule: ^0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin
      macos:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
