name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.1.0
homepage: https://github.com/builttoroam/device_calendar/tree/master

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.8.0
  intl: ^0.17.0
  rrule:
    git:
      url: git://github.com/GoldenSoju/rrule.git
      ref: main
#  rrule:
#    path: ../rrule

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
