name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.3.0
homepage: https://github.com/builttoroam/device_calendar/tree/master

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  sprintf: ^6.0.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  isolate_handler: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"
