name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.0.1
homepage: https://github.com/builttoroam/device_calendar/tree/master

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  collection: ^1.15.0
  sprintf: ^6.0.0
  timezone: ^0.7.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"
