name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 2.0.0
homepage: https://github.com/builttoroam/flutter_plugins/tree/master/device_calendar

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  pedantic: ^1.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# This is a workaround since v1.9.0 cannot be used as a main dependency: https://github.com/dart-lang/pedantic/issues/46
dependency_overrides:
  pedantic: 1.9.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"