# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [develop, release, hotfix, master]
  pull_request:
    branches: [develop, release, hotfix, master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version
      - run: flutter test
      - name: publish test
        run: flutter pub publish --dry-run
      - name: android build
        run: |
          cd example
          flutter build appbundle
          flutter build apk
  test-ios:
    name: iOS build test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version
      - name: iOS build
        run: |
          cd example
          flutter build ios --release --no-codesign
